
###

POST http://127.0.0.1:8000/users/signup
Content-Type: application/json

{
  "username": "admin5",
  "password": "admin",
  "email": "itg51649@fosiq.com"
}


###

POST http://127.0.0.1:8000/users/login
Content-Type: application/json

{
  "username": "your_username",
  "password": "your_password"
}

###

GET http://127.0.0.1:8000/users/test_token
Content-Type: application/json
Authorization: Token c55d9202dda19f62f656ab8016a613567098fd06

###


POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "admin5",
  "password": "admin"
}

###

POST http://127.0.0.1:8000/users/wannaresetpass/
Content-Type: application/json

{
  "email": "mta20870@zbock.com"
}

###


###

GET http://127.0.0.1:8000/users/mailconfirm/Mg/c3ua42-827155014db6d7f41a579791010d5a3f/
Content-Type: application/json




###

POST http://127.0.0.1:8000/users/wannaresetpass/
Content-Type: application/json

{
  "email": "your_email@qwerty.com"
}

###

POST http://127.0.0.1:8000/users/resetpass/MQ/byuvr9-c98cb7763d2e781c97076eacd569da02/
Content-Type: application/json

{
  "new_password": "your_new_password"
}

###

POST http://127.0.0.1:8000/users/post_transaction
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE1NTExNTExLCJpYXQiOjE3MTUxNjU5MTEsImp0aSI6ImJmYmIzYjZhNjI5YjRkOTNhNzgwZWY4ZWIxYjA3ZjljIiwidXNlcl9pZCI6NX0.hdv6y2z2_jUpxy_pGDRSWU9HI-qlSEzGun3c6UhFOog


{
  "category": "entertainment ",
  "amount": "-1000",
  "time": "2023-11-26",
  "description": "",
  "currency": "zl"
}

###

GET http://127.0.0.1:8000/users/get_transaction
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2ODAzNDYwLCJpYXQiOjE3MTY0NTc4NjAsImp0aSI6IjlmYzAwMGM0NzM2YzQyYWQ4NjcxNGUzNWVkYjFiZjgxIiwidXNlcl9pZCI6M30.SXHOznHdi90s9GrpLrH6A9rZwRZj39RdN454cmVdT-w

{
  "end_amount": "10000",
  "start_amount": "-10000",
  "start_time": "2023-10-21 00:00:00",
  "end_time": "2023-11-15 00:00:00"
}

###

DELETE http://127.0.0.1:8000/users/delete_transaction/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE1NTExNTExLCJpYXQiOjE3MTUxNjU5MTEsImp0aSI6ImJmYmIzYjZhNjI5YjRkOTNhNzgwZWY4ZWIxYjA3ZjljIiwidXNlcl9pZCI6NX0.hdv6y2z2_jUpxy_pGDRSWU9HI-qlSEzGun3c6UhFOog

{
  "id": "4"
}

###

GET http://127.0.0.1:8000/users/get_userdata/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE1NTExNTExLCJpYXQiOjE3MTUxNjU5MTEsImp0aSI6ImJmYmIzYjZhNjI5YjRkOTNhNzgwZWY4ZWIxYjA3ZjljIiwidXNlcl9pZCI6NX0.hdv6y2z2_jUpxy_pGDRSWU9HI-qlSEzGun3c6UhFOog

###

POST http://127.0.0.1:8000/users/create_event/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE1NTExNTExLCJpYXQiOjE3MTUxNjU5MTEsImp0aSI6ImJmYmIzYjZhNjI5YjRkOTNhNzgwZWY4ZWIxYjA3ZjljIiwidXNlcl9pZCI6NX0.hdv6y2z2_jUpxy_pGDRSWU9HI-qlSEzGun3c6UhFOog

{
  "title": "event1",
  "start_time": "2023-10-21 00:00:00",
  "end_time": "2023-10-21 00:00:00"
}

###

DELETE http://127.0.0.1:8000/users/delete_event/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE1NTExNTExLCJpYXQiOjE3MTUxNjU5MTEsImp0aSI6ImJmYmIzYjZhNjI5YjRkOTNhNzgwZWY4ZWIxYjA3ZjljIiwidXNlcl9pZCI6NX0.hdv6y2z2_jUpxy_pGDRSWU9HI-qlSEzGun3c6UhFOog

{
  "id": "27"
}

###

GET http://127.0.0.1:8000/users/get_events/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE1NTExNTExLCJpYXQiOjE3MTUxNjU5MTEsImp0aSI6ImJmYmIzYjZhNjI5YjRkOTNhNzgwZWY4ZWIxYjA3ZjljIiwidXNlcl9pZCI6NX0.hdv6y2z2_jUpxy_pGDRSWU9HI-qlSEzGun3c6UhFOog

###

PATCH http://127.0.0.1:8000/users/patch_event/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE1NTExNTExLCJpYXQiOjE3MTUxNjU5MTEsImp0aSI6ImJmYmIzYjZhNjI5YjRkOTNhNzgwZWY4ZWIxYjA3ZjljIiwidXNlcl9pZCI6NX0.hdv6y2z2_jUpxy_pGDRSWU9HI-qlSEzGun3c6UhFOog

{
  "id": "29",
  "start_time": "2023-11-21 00:00:00",
  "end_time": "2023-11-21 01:00:00"
}

###

POST http://127.0.0.1:8000/users/create_actives/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2ODAwNjg5LCJpYXQiOjE3MTY0NTUwODksImp0aSI6ImU4ZTdjNjY2MmJhMzQ0NTNiZjhiOWM3MTM5ZDY3NTJhIiwidXNlcl9pZCI6M30.edwW8ItnzL5ttzt7ND4rDGU-HskR3PofPEJDkQqCBmU

{
  "name": "test",
  "price": "80",
  "category": "pp",
  "date": "2023-10-21T00:00:00Z"
}

###
DELETE http://127.0.0.1:8000/users/delete_actives/?id=60
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE1OTc1Mjk2LCJpYXQiOjE3MTU2Mjk2OTYsImp0aSI6ImFmODc5ZTZjNDQ5MjRjNTZhM2ExYzhhYjFhMTY3NjljIiwidXNlcl9pZCI6N30.d8KOorVfY2JJX-2A8JjGh3tYcxiRsoND71wkDq3WNu8

###

GET http://127.0.0.1:8000/users/get_actives/?id=77
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE1OTc1Mjk2LCJpYXQiOjE3MTU2Mjk2OTYsImp0aSI6ImFmODc5ZTZjNDQ5MjRjNTZhM2ExYzhhYjFhMTY3NjljIiwidXNlcl9pZCI6N30.d8KOorVfY2JJX-2A8JjGh3tYcxiRsoND71wkDq3WNu8

###

PUT http://127.0.0.1:8000/users/update_actives/?id=7&new_price=80&date=2023-10-21T00:00:00Z
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2ODAzNDYwLCJpYXQiOjE3MTY0NTc4NjAsImp0aSI6IjlmYzAwMGM0NzM2YzQyYWQ4NjcxNGUzNWVkYjFiZjgxIiwidXNlcl9pZCI6M30.SXHOznHdi90s9GrpLrH6A9rZwRZj39RdN454cmVdT-w


###

GET http://127.0.0.1:8000/users/get_price_history/?id=7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2ODAzNDYwLCJpYXQiOjE3MTY0NTc4NjAsImp0aSI6IjlmYzAwMGM0NzM2YzQyYWQ4NjcxNGUzNWVkYjFiZjgxIiwidXNlcl9pZCI6M30.SXHOznHdi90s9GrpLrH6A9rZwRZj39RdN454cmVdT-w

###

GET http://127.0.0.1:8000/users/get_all_actives/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2ODAzNDYwLCJpYXQiOjE3MTY0NTc4NjAsImp0aSI6IjlmYzAwMGM0NzM2YzQyYWQ4NjcxNGUzNWVkYjFiZjgxIiwidXNlcl9pZCI6M30.SXHOznHdi90s9GrpLrH6A9rZwRZj39RdN454cmVdT-w

###

GET http://127.0.0.1:8000/users/get_all_users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2ODAzNDYwLCJpYXQiOjE3MTY0NTc4NjAsImp0aSI6IjlmYzAwMGM0NzM2YzQyYWQ4NjcxNGUzNWVkYjFiZjgxIiwidXNlcl9pZCI6M30.SXHOznHdi90s9GrpLrH6A9rZwRZj39RdN454cmVdT-w

###
